import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {auth}  from 'firebase/compat/app'
import { useAuth } from '../lib/auth'
const Home= ()=> {
  const auth= useAuth()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Feedback Log
        </h1>
        <button onClick={(e) => auth.signinWithGithub()}>Sign In</button>  
        <button onClick={(e) => auth.signout()}>Sign out</button>  

      <section>
        {JSON.stringify(auth.user)}
      </section>
      </main>

    </div>
  )
}
export default Home
